spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.dockerwebbooklibrary.mongock.changelog
